// Smoke test: run game.js against a stub DOM and check the scoring.
const el = () => ({ classList: { toggle() {}, remove() {}, add() {} }, style: { setProperty() {} }, insertAdjacentHTML() {}, appendChild() {}, append() {}, firstChild: { firstChild: {} }, value: '', focus() {} });
const els = {};
global.window = {}; global.localStorage = { getItem: () => null, setItem() {} };
global.setInterval = () => 0; global.clearInterval = () => {}; global.setTimeout = () => 0;
global.requestAnimationFrame = () => {}; global.performance = { now: () => 0 };
global.document = { getElementById: id => els[id] || (els[id] = el()), body: el(), createElement: el };
require('./data.js');
const src = require('fs').readFileSync('game.js', 'utf8') + ';module.exports={score,PROMPTS,NICHE,dailySet}';
const m = new module.constructor(); m._compile(src, 'game.js');
const { score, PROMPTS, NICHE, dailySet } = m.exports;
const assert = require('assert');
const fruit = PROMPTS.find(p => p.q === 'Name a fruit');
assert.equal(score(fruit, 'Apple').m, 10);
assert.equal(score(fruit, 'apples').m, 10);
assert.equal(score(fruit, 'cloudberry').m, 100);
assert.equal(score(fruit, 'pizza'), 'invalid');
assert.equal(score(fruit, '  '), null);
assert.equal(dailySet().length, 7);
assert(dailySet().every(p => NICHE.includes(p)));
console.log('ok; today:', dailySet().map(p => p.q).join(' / '));
